FROM gradle:8.5.0-jdk8

# Install netcat for healthcheck support
RUN apt-get update && \
    apt-get install -y netcat-traditional && \
    rm -rf /var/lib/apt/lists/*

# Copy entrypoint script
COPY infra/docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh

WORKDIR /app

ENTRYPOINT ["/docker-entrypoint.sh"]
